### ISSUE TITLE
Cannot compile on linux, gcc 4.7.2

### ISSUE THREAD

**Issue by romain145** [EricConnerApps/wpclp#1]
The "MAKEFILE" should be names "Makefile" for compatibility.

make output:
```
romain@HP1:~/wpclp$ make
gcc -c -Wall -I. wpc_lamp_patcher.c -o wpc_lamp_patcher.o
gcc -c -Wall -I. wpc_rom.c -o wpc_rom.o
gcc -c -Wall -I. wpc_lampmatrix_patch.c -o wpc_lampmatrix_patch.o
gcc  wpc_lamp_patcher.o wpc_rom.o wpc_lampmatrix_patch.o  -o WPCGhost
wpc_rom.o:(.bss+0x0): multiple definition of `debug'
wpc_lamp_patcher.o:(.bss+0x0): first defined here
wpc_rom.o:(.bss+0x4): multiple definition of `force'
wpc_lamp_patcher.o:(.bss+0x4): first defined here
wpc_rom.o:(.bss+0x8): multiple definition of `skip_patch'
wpc_lamp_patcher.o:(.bss+0x8): first defined here
wpc_rom.o:(.bss+0xc): multiple definition of `extra_delay'
wpc_lamp_patcher.o:(.bss+0xc): first defined here
wpc_rom.o: In function `prog_info':
wpc_rom.c:(.text+0x0): multiple definition of `prog_info'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x0): first defined here
wpc_rom.o: In function `help_exit':
wpc_rom.c:(.text+0x60): multiple definition of `help_exit'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x60): first defined here
wpc_rom.o: In function `get_text':
wpc_rom.c:(.text+0xff): multiple definition of `get_text'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0xff): first defined here
wpc_rom.o: In function `load_file':
wpc_rom.c:(.text+0x19a): multiple definition of `load_file'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x19a): first defined here
wpc_rom.o: In function `write_file':
wpc_rom.c:(.text+0x2bc): multiple definition of `write_file'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x2bc): first defined here
wpc_rom.o: In function `get_new_rom_version':
wpc_rom.c:(.text+0x379): multiple definition of `get_new_rom_version'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x379): first defined here
wpc_rom.o: In function `main':
wpc_rom.c:(.text+0x7eb): multiple definition of `main'
wpc_lamp_patcher.o:wpc_lamp_patcher.c:(.text+0x7eb): first defined here
wpc_lamp_patcher.o: In function `main':
wpc_lamp_patcher.c:(.text+0xb58): undefined reference to `wpc_validate_rom'
wpc_lamp_patcher.c:(.text+0xb71): undefined reference to `wpc_validate_rom'
wpc_lamp_patcher.c:(.text+0xb9a): undefined reference to `wpc_print_rom_info'
wpc_lamp_patcher.c:(.text+0xbb5): undefined reference to `wpc_print_rom_info'
wpc_lamp_patcher.c:(.text+0xcfe): undefined reference to `wpc_update_rom_version_checksum'
wpc_lamp_patcher.c:(.text+0xd3e): undefined reference to `wpc_print_rom_info'
wpc_lamp_patcher.c:(.text+0xf19): undefined reference to `wpc_validate_rom'
wpc_lamp_patcher.c:(.text+0xf42): undefined reference to `wpc_print_rom_info'
wpc_lamp_patcher.c:(.text+0xf67): undefined reference to `wpc_print_rom_info'
wpc_rom.o: In function `main':
wpc_rom.c:(.text+0xb58): undefined reference to `wpc_validate_rom'
wpc_rom.c:(.text+0xb71): undefined reference to `wpc_validate_rom'
wpc_rom.c:(.text+0xb9a): undefined reference to `wpc_print_rom_info'
wpc_rom.c:(.text+0xbb5): undefined reference to `wpc_print_rom_info'
wpc_rom.c:(.text+0xcfe): undefined reference to `wpc_update_rom_version_checksum'
wpc_rom.c:(.text+0xd3e): undefined reference to `wpc_print_rom_info'
wpc_rom.c:(.text+0xf19): undefined reference to `wpc_validate_rom'
wpc_rom.c:(.text+0xf42): undefined reference to `wpc_print_rom_info'
wpc_rom.c:(.text+0xf67): undefined reference to `wpc_print_rom_info'
wpc_lampmatrix_patch.o: In function `wpc_patch_lamp_matrix':
wpc_lampmatrix_patch.c:(.text+0x171): undefined reference to `search_for_sig'
wpc_lampmatrix_patch.c:(.text+0x285): undefined reference to `search_for_sig'
wpc_lampmatrix_patch.c:(.text+0x38b): undefined reference to `search_for_sig'
wpc_lampmatrix_patch.c:(.text+0x4a6): undefined reference to `search_for_sig'
wpc_lampmatrix_patch.c:(.text+0x557): undefined reference to `search_for_sig'
wpc_lampmatrix_patch.o:wpc_lampmatrix_patch.c:(.text+0x608): more undefined references to `search_for_sig' follow
collect2: error: ld returned 1 exit status
make: *** [WPCGhost] Error 1

```

**Comment by eaconner** [comment]
I recommend using gcc 4.2.4. It compiles fine for me with that version.

**Comment by romain145** [comment]
Some functions cannot be found in the files with grep:
prog_info, get_text, load_file, write_file, get_new_rom_version.
I am wondering if a file could be missing from your commit?

**Comment by eaconner** [comment]
It looks like wpc_rom.c was the wrong file for some reason. I replaced it and everything should build now.
